  <footer role="contentinfo">
      <p>&copy; 2025 CyberSecure Solutions Inc. All rights reserved.</p>
      <a href="https://github.com/105517068/team-website.git" target="_blank">GitHub Repository</a> |
      <a href="https://thrishulanimsara111-1758724044663.atlassian.net/jira/software/projects/SCRUM/boards/1/timeline?atlOrigin=eyJpIjoiNWQ5YzRmZmQ1MjY0NDhiY2E5NmM3NzQzNDNhZjkyYjkiLCJwIjoiaiJ9" target="_blank">Jira Board</a> | 
      <a href="mailto:info@cybersecuresolutions.com">info@cybersecuresolutions.com</a>
  </footer>

</body>
</html>