<!-- footer.inc -->
<footer>
  <p>&copy; 2025 CyberSecure Solutions Inc. All rights reserved.</p>
  <a href="https://github.com/105517068/team-website.git" target="_blank">GitHub Repository</a> |
  <a href="https://thrishulanimsara111-1758724044663.atlassian.net/jira/software/projects/SCRUM/boards/1/timeline" target="_blank">Jira Board</a> | 
  <a href="mailto:info@cybersecuresolutions.com">info@cybersecuresolutions.com</a>
</footer>